import { type NextPage } from "next";
import Head from "next/head";
import logoImage from "../assets/logo.png";
import Image from "next/image";
import { Hero } from "~/components/hero";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="flex w-full flex-col px-40 py-2">
        <header className="flex items-center justify-center gap-4">
          <div className="mr-14">
            <Image
              src={logoImage}
              alt={"Logo da MR Imobiliaria"}
              quality={100}
              width={270}
            />
          </div>
          <ul className="flex w-full gap-4 text-xl font-semibold">
            <li>
              <a href="#">Home </a>
            </li>
            <li>
              <a href="#"> Buy </a>
            </li>
            <li>
              <a href="#"> Sell </a>{" "}
            </li>
            <li>
              <a href="#"> Listed </a>{" "}
            </li>
            <li>
              <a href="#"> Review </a>
            </li>
          </ul>
          <div className="flex w-full justify-end gap-4">
            <button className="rounded-lg border-[3px] border-green-800 bg-transparent px-8 py-3 font-bold text-green-800 hover:border-transparent hover:bg-green-700 hover:text-white">
              Entrar
            </button>
            <button className="rounded-lg border border-green-700 bg-green-800 px-8 py-3 font-semibold text-white hover:bg-green-700">
              Registrar
            </button>
          </div>
        </header>
        <main>
          <Hero />
        </main>
      </div>
    </>
  );
};

export default Home;
